const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const sourceDir = path.join(rootDir, "src");
const outputFile = path.join(rootDir, "main.js");

const files = [
  "core/bootstrap.js",
  "core/config.js",
  "ui/menu.js",
  "automation/big-cookie.js",
  "automation/golden-cookies.js",
  "automation/seasons.js",
  "automation/wrinklers.js",
  "strategy/combos.js",
  "strategy/banking.js",
  "automation/grimoire.js",
  "automation/garden.js",
  "automation/pantheon.js",
  "strategy/buying.js",
  "core/format.js",
  "strategy/ascension.js",
  "ui/status.js",
  "automation/auto-buyer.js",
  "core/lifecycle.js",
];

const header = [
  "// Generated by scripts/build.js. Edit files in src/ instead.",
  "// This bundled file is kept at the repo root for Game.LoadMod/bookmarklet loading.",
  "",
].join("\n");

const body = files
  .map(function (file) {
    const filePath = path.join(sourceDir, file);
    if (!fs.existsSync(filePath)) throw new Error("Missing source file: " + filePath);
    return fs.readFileSync(filePath, "utf8").trimEnd();
  })
  .join("\n\n");

fs.writeFileSync(outputFile, header + body + "\n");
